### ISSUE TITLE
Suggestions for optimizing the icon bar at the top of the tool on the right

### ISSUE THREAD

**Issue by syshlang** [zaheralmajed/vicious-theme-obsidian#1]
For the icon bar at the top of the tool on the right, it is recommended to slide left and right to prevent the icon from deforming.
![image](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/8163995/1214ff8d-0d29-4cf8-8599-7e6e6a0b243d)

**Comment by zaheralmajed** [comment]
I'm happy to inform you that this issue has been fixed!

Thank you for your suggestion regarding the icon bar at the top of the tool. Sliding left and right to prevent the icon from deforming is indeed a good recommendation. This approach helps maintain the integrity and visual quality of the icons, ensuring they remain clear and recognizable to users. Your input is greatly appreciated!
