### ISSUE TITLE
Adapt theme to Obsidian v1.6.0

### ISSUE THREAD

**Issue by Wayneoween** [zaheralmajed/vicious-theme-obsidian#10]
Thank you for your work on the theme, I really enjoy the colors and feel of it and I think it is very well balanced.

I am aware that [Obsidian `v1.6.0`](https://obsidian.md/changelog/) is a Catalyst/Prerelease version and in active development so I understand that an update might just not be in the books before it is released to the public.

I think there are more places where this theme isn't applied any more but most noticeably the `Files` Tab/Files Browser is missing all colors.

**Comment by fakepilot** [comment]
I was going to write about this as well. Colors on folders broken on 1.6.0.
PS. Love your theme, the one I use!

**Comment by zaheralmajed** [comment]
Thank you for your kind words. I'm pleased to inform you that the issue you mentioned has been resolved. Please update to the latest version of the theme to see the improvements.
