### ISSUE TITLE
Task Highlight on canvas not displaying correctly in read mode

### ISSUE THREAD

**Issue by n8himmel** [zaheralmajed/vicious-theme-obsidian#11]
See image: Edit vs Read mode on canvas

**Note embedded on canvas, read mode:** 
- Single Task Highlight items do not expand to the end of page as expected
- Task Highlight with subitems. Subitems inherit formatting of parent, but should not

<img width="544" alt="image" src="https://github.com/zaheralmajed/vicious-theme-obsidian/assets/26195744/0cbb0fec-3111-4199-8018-42e3f12a1a7e">

Obsidian v.1.6.3
Vicious 1.1.0

**Comment by zaheralmajed** [comment]
Please share the file with dummy data so I can see the problem you're facing.
I didn't fully understand the issue from your previous description.

**Comment by n8himmel** [comment]
[obs.zip](https://github.com/user-attachments/files/16048886/obs.zip)
https://somup.com/cZiV1pEaKU

Sample and video attached. Thanks for checking

**Comment by zaheralmajed** [comment]
The way I understand it, anything listed under the "Task Highlight" section should be considered complete tasks, any subtasks underneath will be considered as completed. 

As for the width of the "Task Highlight", you mentioned I'll address that in the next version. thanks for the clarification!

Let me know if you have any other questions!

**Comment by n8himmel** [comment]
> The way I understand it, anything listed under the "Task Highlight" section should be considered complete tasks, any subtasks underneath will be considered as completed
---
I don't know on what that understanding is based and it seems unrelated to this issue. The subtasks are being highlighted (on canvas) but should not be, regardless of their state. This issue occurs only on the canvas; otherwise, it works correctly.

I think both problems are related.

Thanks for looking into this.
