### ISSUE TITLE
Markdown line

### ISSUE THREAD

**Issue by eluan7** [zaheralmajed/vicious-theme-obsidian#12]
I have made the numbering exactly the same 1. and 2. but there is a line that goes from the numbering 2. to the end of the page and crosses out all further numbering.

![Fail](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/162610073/717ece51-e92e-4ded-8ae3-8e7faec0f71e)

![image](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/162610073/aab2bfe3-f5f8-4d09-8f57-773eec4cba00)

would be nice if someone could fix this, so that i can use it again without issues

**Comment by zaheralmajed** [comment]
Hi, 

Use TAB instead of SPACE and remove any SPACE before you create the numbering 

**Wrong:**
```
   2. title
```


**Correct :**
```
2. title
```
