### ISSUE TITLE
Flicker and content missing under fullscreen mode on Mac

### ISSUE THREAD

**Issue by xiaomei7** [zaheralmajed/vicious-theme-obsidian#13]
Obsidian v1.6.3
Vicious v1.1.0

Window mode seems fine.
Looks pretty bad, wherever I move my cursor the screen flickers and all the contents looks black, even under system setting, see pic:

<img width="1304" alt="Screenshot 2024-06-14 at 10 14 55" src="https://github.com/zaheralmajed/vicious-theme-obsidian/assets/16567119/ba58fa18-4310-4781-ac2b-b789b6fb6b02">

**Comment by zaheralmajed** [comment]
Try delete and reinstall the theme.
I am using Mac I tried the fullscreen mode and I dont have this issue.
