### ISSUE TITLE
Scroll bars don't work

### ISSUE THREAD

**Issue by zhouxinghong** [zaheralmajed/vicious-theme-obsidian#17]
Hello! Thank you for a great theme
Scrollbars don't work and reset button doesn't work

![image](https://github.com/user-attachments/assets/ed7bc9e0-956d-4ee0-9f84-e1a3d0a54644)

Windows 10
Obsidian 1.6.7

**Comment by zaheralmajed** [comment]
provide more information and screenshot please, please try to update obsidian and the theme

**Comment by zhouxinghong** [comment]
![image](https://github.com/user-attachments/assets/73af13de-e018-4796-ac95-2fde133873e7)
![image](https://github.com/user-attachments/assets/fd97bd49-7f7f-4fce-8766-81930d81bf8a)
![image](https://github.com/user-attachments/assets/d1f2e4a2-d90e-4f38-8267-cfc99547c8a6)
![image](https://github.com/user-attachments/assets/e67418b1-cee0-4bce-9a28-457dad1b88de)

**Comment by zhouxinghong** [comment]
![image](https://github.com/user-attachments/assets/8a4e0596-60ad-4f2b-9d5e-b1e1bd32cb57)

**Comment by zhouxinghong** [comment]
Windows 10
Obsidian 1.6.7

**Comment by zaheralmajed** [comment]
Fixed, please update the theme.
