### ISSUE TITLE
Obsidian - selection

### ISSUE THREAD

**Issue by techno-sopher** [zaheralmajed/vicious-theme-obsidian#18]
When a sentence is selected, the selection does not look obvious. It blends with the dark theme making it difficult to see the selection. It would very helpful if the highlight colour is different.

![Screenshot 2024-08-27 152507](https://github.com/user-attachments/assets/1c154fc0-589f-4a67-88dc-333d6010da38)

**Comment by zaheralmajed** [comment]
Fixed, please update the theme.
