### ISSUE TITLE
Lines while numbering

### ISSUE THREAD

**Issue by techno-sopher** [zaheralmajed/vicious-theme-obsidian#19]
I have attached a screen recording where we can see lines running over the numbering and it hinders the visibility of bullet and other content. Which functionally and aesthetically unappealing.
 
https://github.com/user-attachments/assets/a3c043ac-8ecb-4bce-aea7-64b74e6c30c2

**Comment by zaheralmajed** [comment]
Take a look at #4

**Comment by techno-sopher** [comment]
thank you.
