### ISSUE TITLE
Outliner indention error

### ISSUE THREAD

**Issue by fakepilot** [zaheralmajed/vicious-theme-obsidian#2]
Not sure this is the Theme's error or Outliner. But if you have a list, with an indention and a todo.
You get this double line, looks like this:
![image](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/4529789/9b3a227d-8be7-4a41-92d3-44fa04869986)
Really love the theme, this is the only thing I can't seem to get around myself.

**Comment by zaheralmajed** [comment]
Hi, did you update to the latest version of the theme?

**Comment by fakepilot** [comment]
Yes, checked for updates now, update all, and restart. Problem is still there. Could it be a Windows thing? I'm on Win 10 Pro.

**Comment by fakepilot** [comment]
It works on my iPhone, but not on my PC. So I'm guessing this is some Windows CSS problem.

**Comment by zaheralmajed** [comment]
Thank you for bringing this issue to our attention. I'm happy to let you know that the problem has been fixed. To resolve the double line issue you described, please ensure that you have the latest version of the theme. Also, now you can install "Style Settings" plugin to customize various aspects of your theme, including show/hide indentations.

I appreciate your feedback and hope that you continue to enjoy using the theme.

**Comment by fakepilot** [comment]
Yes, thanks! Can confirm, it's fixed. <3
