### ISSUE TITLE
My fav theme, but one BIG request.

### ISSUE THREAD

**Issue by vdruts** [zaheralmajed/vicious-theme-obsidian#3]
Can we please have more settings in "Style settings" plugin? Especially want (scroll bars). I have some very long documents and with scroll bars missing, it's incredibly cumbersome and slow to navigate them.

**Comment by zaheralmajed** [comment]
Thank you for your feedback regarding the "Style settings" plugin.

I'm glad to inform you that the issue you mentioned has been resolved. The latest version of the theme now includes few settings, including the ability to hide or show scroll bars. To take advantage of these new features, please make sure to update or install the latest version of the "Style settings" plugin. Once installed, you'll have the option to customize the visibility of scroll bars according to your preferences. This should greatly improve your experience when navigating long documents.
