### ISSUE TITLE
Indentation styles, infinite line

### ISSUE THREAD

**Issue by fev4** [zaheralmajed/vicious-theme-obsidian#4]
Hi there,

Just found out about this theme and looks amazing.

I was confused as to why the indentation lines looked so long. Here's a demo:

![Obsidian_FJUVwNpQYG](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/16828078/c27cac16-a7ec-4a8d-83b5-4c3e20ebf309)

I've deactivated all my addons and here's how it looks:
![Obsidian_ltqU6Fr1fE](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/16828078/10115a7a-b383-4e6f-b84e-734597efac42)

It seems to be on only the first indentation and it works correctly afterwards.

I'm using version 1.0.8 of the theme. My system is Windows 11 and Obsidian is in version 1.5.3.

Please let me know if there's any other info I can help provide in order to further debug the issue.
Happy to help

**Comment by fev4** [comment]
For now I've deactivated the indents by using the Style Settings as suggested in a different issue. In any case the theme looks amazing, thanks for all the effort put into it.

**Comment by zaheralmajed** [comment]
Hi,

Please remove any space/tab before the numbering.

The indentation is very sensitive to any space before because is calculate the amount the space you have to draw the line. for example:

`1. this is ok!`

` 1. this is not ok!`  

can you check and let me know.

**Comment by fev4** [comment]
hey @zaheralmajed thanks for responding

this is what I'm seeing:
![Obsidian_0k548ezd74](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/16828078/b9c8cd8d-a16c-4abf-b07e-7c033fe37699)
![Obsidian_ttL94N9pfy](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/16828078/d2dbdda1-e5b8-4431-9a47-fbf963aae702)

The first bullet point doesn't have a manual extra space at the beginning. But as soon as I enter a point (1.) it auto indents. Is this what you are referring to? To be clear I'm not manually entering a space before the bullet number.

**Comment by fev4** [comment]
Hey there, just found what the problem was. My tab indentation level was a 2 points. When I reset it back to 4 points, that fixed it.
