### ISSUE TITLE
Transparency on mobile

### ISSUE THREAD

**Issue by wilcovanr** [zaheralmajed/vicious-theme-obsidian#5]
Hi, 
I love the theme.
I use obsidian a lot on my mobile and there I find the following issue.
The bar on the left side of the screen is not hidden as marked in the screenshots.

It would be nice if the underlying bar is completely hidden by the layer above (files, search etc.)

Regards,
Wilco

![WhatsApp Image 2024-01-20 at 07 07 57 (1)](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/154445744/f6d35e8c-0f35-4fb6-9afb-b86bc1fa6936)
![WhatsApp Image 2024-01-20 at 07 07 57](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/154445744/e80f3bc8-b816-4be5-b676-b947bbbf774d)

**Comment by zaheralmajed** [comment]
Thank you for bringing this issue to my attention. I'm happy to let you know that the problem has been fixed. To resolve the issue you described, please ensure that you have the latest version of the theme.

I appreciate your feedback and hope that you continue to enjoy using the theme.
