### ISSUE TITLE
Title bar does not hide

### ISSUE THREAD

**Issue by alex-chris** [zaheralmajed/vicious-theme-obsidian#6]
Hi, I love your theme, it's my favourite so far. I would like to know if you can guide me in fixing a detail. I'm using the plugin beautitab and when I put a new tab does not hide the title bar, do you know if there is a solution? thank you very much!
<img width="1512" alt="Captura de pantalla 2024-04-18 a la(s) 21 32 20" src="https://github.com/zaheralmajed/vicious-theme-obsidian/assets/142114171/3c2ee88b-0488-424c-85ab-36bc68de7c7a">

**Comment by zaheralmajed** [comment]
I'll look into this.

**Comment by zaheralmajed** [comment]
Thank you for your kind words! I'm thrilled to hear that you find the theme to be exceptional. Its beautiful design and captivating colors certainly make it stand out. 

I'm happy to inform you that the issue you mentioned has been addressed. I have made some adjustments to the theme.

Once again, thank you for your positive feedback, and please don't hesitate to reach out if you have any more suggestions or questions.
