### ISSUE TITLE
BOLD, ITALIC and BOLD+ITALIC deserve more attention.

### ISSUE THREAD

**Issue by judah-lopes** [zaheralmajed/vicious-theme-obsidian#7]
Hello,
I am a new convert to note-taking apps for studying. Before, I used notebooks because, whether you like it or not, a pen gives you more freedom to customize your studies.

Anyway, as a "notebooker," I was looking for a good theme that could come close to the advantages of a physical notebook.

I use Dracula+LYT a lot because they have a feature that sets them apart from all the others: besides having a color for each title, the emphasis they give when using **BOLD**, _ITALIC_, ==HIGHLIGHT==, and **_BOLD+ITALIC_** is unique.

HOWEVER... the colors are very vibrant and end up hurting the eyes after prolonged use, so I continue to search for something better. In this search, I found THE VICIOUS! It has everything to be the GOAT, it's much more beautiful than the others, the colors and the interface design are sensational, it just lacks that emphasis for these particular texts...

I would really appreciate it if you could take a look at DRACULA+LYT to get an idea and improve on this point!! 🙏🙏🙏

---

PS: The image below is a snippet of some notes I made at the beginning of my app usage. 
- in dracula + lyt

![imagem_2024-04-21_215659257](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/134812191/58c6117e-fcad-4c09-ade3-742875d327f2)

- in vicious

![image](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/134812191/02de534d-dba4-41a9-84bf-823c23dc63fb)

**Comment by zaheralmajed** [comment]
Good Point. I will look into this.

**Comment by zaheralmajed** [comment]
Thank you for your kind words! I'm thrilled to hear that you find the theme to be exceptional. Its beautiful design and captivating colors certainly make it stand out. I appreciate your feedback regarding the emphasis on particular texts.

I'm happy to inform you that the issue you mentioned has been addressed. I have made some adjustments to the theme by implementing default colors for bold, italics, bold+italics, and highlight. This means that the emphasis on specific texts will now be more prominent and visually appealing.

Additionally, I would like to recommend using the style settings plugin to further customize the default colors according to your preferences. This plugin allows you to modify the theme's appearance and tailor it to your liking. 

![Screenshot 2024-04-22 at 10 41 35 AM](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/142975262/e261fa55-f95e-4f8e-b231-3c900c27977b)

From there, you can make changes to the default colors for bold, italics, bold+italics, and highlight. Experiment with different color combinations until you achieve the desired emphasis.

I hope these adjustments and the availability of the style settings plugin enhance your experience with the theme even further. 

Once again, thank you for your positive feedback, and please don't hesitate to reach out if you have any more suggestions or questions.

**Comment by judah-lopes** [comment]
Brilliant!
Thank you, man. Congrats to tour job!


- before:
![Captura de tela 2024-04-21 220005](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/134812191/323a8b20-866c-4a79-a98b-071ad0024309)

- after:
![Captura de tela 2024-04-22 151240](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/134812191/5c80e6ed-11a1-4bae-b5cc-a026c88edfd2)
