### ISSUE TITLE
Callout Background color

### ISSUE THREAD

**Issue by JigenDD** [zaheralmajed/vicious-theme-obsidian#8]
Hello, I've been enjoying your theme, and I find its general design and direction amazing. I have a suggestion -- both aesthetic and functional -- though.  

Callout generally tend to blend way too much with the rest of the background, and finding color shade (which could be based on the color of the callout itself -- *for example, a callout about "information" having an extremely dark blue background that goes with the pitch black dark mode)*  would greatly improve readability on some screens. 

For example, I have a great gaming monitor on my main rig, and with its refresh rates and good color depth I can discern the callouts as they are. But on my medium range office laptop, the same doesn't happen and I have a hard time discerning callouts, **especially** where they end, given that there's only a thin border at the end. 

All in all, a background color based on the callout color would improve things a lot. If you're in doubt, you could make it optional in the style settings menu. Thanks in advance!

**Comment by zaheralmajed** [comment]
I have made some updates based on your suggestion. Please ensure that you have the latest version installed.

Feel free to select the style that suits your preferences. If you have any further suggestions or feedback, please let me know.

---

In the style settings, you will now find four different callout styles to choose from. These options are:

## Default
![01](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/142975262/9518b056-6bed-49b9-86dd-73e8d9c913b1)


## Static
![02](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/142975262/4e94fe85-41f3-4fa4-b775-791027fac89b)


## Vibrant
![03](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/142975262/b67e02ab-a82f-4802-a3bb-34f6e34f2074)


## One Color
![04](https://github.com/zaheralmajed/vicious-theme-obsidian/assets/142975262/fd9325aa-3a0f-492b-98ae-89da416c1bf7)
