### ISSUE TITLE
Colour customisation

### ISSUE THREAD

**Issue by alex-chris** [zaheralmajed/vicious-theme-obsidian#9]
Hello again! I really like the colour customisation update, but I have a problem, they only show in edit mode, when I go back to read mode bold color and italic color they show in pink.

<img width="1287" alt="Captura de pantalla 2024-05-08 a la(s) 13 12 44" src="https://github.com/zaheralmajed/vicious-theme-obsidian/assets/142114171/9bc61a4f-b435-45a7-a65c-c952752304e6">

**Comment by zaheralmajed** [comment]
I'm pleased to inform you that the issue you mentioned has been resolved. Please update to the latest version of the theme to see the improvements.
